In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
df=pd.read_csv('madrid_variables.csv')
df.head(5)

Unnamed: 0  host_response_rate  host_acceptance_rate  \
0           0                 1.0                  1.00   
1           1                 0.0                  0.57   
2           2                 1.0                  1.00   
3           3                 0.9                  0.33   
4           4                 0.9                  0.80   

   host_total_listings_count   latitude  accommodates  bathrooms  \
0                        1.0  40.406980           2.0        1.0   
1                        4.0  40.392100           2.0        1.0   
2                        2.0  40.395110           1.0        1.0   
3                        1.0  40.395555           3.0        1.0   
4                        4.0  40.430450           1.0        1.0   

   minimum_nights  number_of_reviews  bedrooms  reviews_per_month  price  \
0             1.0                2.0       1.0               0.61   68.0   
1             1.0                3.0       1.0               0.28   16.0   
2             1.0              186.0       2.0               5.40   25.0   
3             2.0                1.0       1.0               0.14   26.0   
4             7.0                0.0       1.0               1.90  100.0   

  host_is_superhost host_has_profile_pic host_identity_verified  \
0                 f                    t                      t   
1                 f                    t                      t   
2                 f                    t                      t   
3                 f                    t                      t   
4                 f                    t                      t   

  has_availability instant_bookable  
0                t                f  
1                t                f  
2                t                t  
3                t                f  
4                t                f

In [4]:
df['host_is_superhost'] = df['host_is_superhost'].replace({
    't': 'yes',
    'f': 'no',
    'VALIDACIÓN PENDIENTE': np.nan
})

df['host_has_profile_pic'] = df['host_has_profile_pic'].replace({
    't': 'yes',
    'f': 'no',
    'INFORMACIÓN FALTANTE': np.nan
})

df['host_identity_verified'] = df['host_identity_verified'].replace({
    't': 'yes',
    'f': 'no',
    'INFORMACIÓN FALTANTE': np.nan
})

df['has_availability'] = df['has_availability'].replace({
    't': 'yes',
    'f': 'no',
    'INFORMACIÓN NO DISPONIBLE': np.nan
})

df['instant_bookable'] = df['instant_bookable'].replace({
    't': 'yes',
    'f': 'no',
    'INFORMACIÓN NO DISPONIBLE': np.nan
})

df =df.fillna(method="bfill")
df =df.fillna(method="ffill")

<ipython-input-4-d98a12bdaf1e>:31: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="bfill")
<ipython-input-4-d98a12bdaf1e>:32: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="ffill")


In [ ]:
df['host_has_profile_pic'].unique()

array(['yes', 'no'], dtype=object)

In [ ]:
df["host_has_profile_pic"].head(30)

0     yes
1     yes
2     yes
3     yes
4     yes
5     yes
6     yes
7     yes
8      no
9     yes
10     no
11    yes
12    yes
13    yes
14    yes
15    yes
16     no
17     no
18     no
19    yes
20    yes
21     no
22     no
23     no
24     no
25     no
26     no
27    yes
28    yes
29     no
Name: host_identity_verified, dtype: object

MODELO 1 host_is_superhost

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "reviews_per_month", "bedrooms"]]
Var_Dep=df["host_is_superhost"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[6085   83]
 [1845   65]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="yes")
print("precision del modelo:")
print(precision)

precision del modelo:
0.4391891891891892


In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.7613270611537509


In [ ]:
#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
0.034031413612565446


MODELO 2 host_has_profile_pic

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "reviews_per_month", "bedrooms"]]
Var_Dep=df["host_has_profile_pic"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  224]
 [   0 7854]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="yes")
print("precision del modelo:")
print(precision)

precision del modelo:
0.9722703639514731


In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.9722703639514731


In [ ]:
#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
1.0


MODELO 3 host_identity_verified

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "reviews_per_month", "bedrooms"]]
Var_Dep=df["host_identity_verified"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  666]
 [   0 7412]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="yes")
print("precision del modelo:")
print(precision)

In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

In [ ]:
#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

MODELO has_availability

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "reviews_per_month", "bedrooms"]]
Var_Dep=df["has_availability"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0   27]
 [   0 8051]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="yes")
print("precision del modelo:")
print(precision)

precision del modelo:
0.9966575885120079


In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

In [ ]:
#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

------------------------------

---------------

---------------

Creación de categorías a partir de clases

host_acceptance_rate

In [5]:
Max=df["host_acceptance_rate"].max()
Min=df["host_acceptance_rate"].min()
Limites=[Min, Max]
Limites


[0.0, 1.0]

In [6]:
#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(-0.1,1.1,3)
intervalos

#Crear las categorías
categorias=["Aceptacion baja", "Aceptacion alta"]

df["host_acceptance_rate"]=pd.cut(x=df["host_acceptance_rate"], bins=intervalos, labels=categorias)

df["host_acceptance_rate"]

0        Aceptacion alta
1        Aceptacion alta
2        Aceptacion alta
3        Aceptacion baja
4        Aceptacion alta
              ...       
26920    Aceptacion baja
26921    Aceptacion alta
26922    Aceptacion alta
26923    Aceptacion alta
26924    Aceptacion alta
Name: host_acceptance_rate, Length: 26925, dtype: category
Categories (2, object): ['Aceptacion baja' < 'Aceptacion alta']

host_response_rate

In [7]:
Max=df["host_response_rate"].max()
Min=df["host_response_rate"].min()
Limites=[Min, Max]
Limites



[0.0, 1.0]

In [8]:
#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(-0.1, 1.1,3)
intervalos

#Crear las categorías
categorias=["Respuesta baja", "Respuesta alta"]

df["host_response_rate"]=pd.cut(x=df["host_response_rate"], bins=intervalos, labels=categorias)

df["host_response_rate"]

0        Respuesta alta
1        Respuesta baja
2        Respuesta alta
3        Respuesta alta
4        Respuesta alta
              ...      
26920    Respuesta alta
26921    Respuesta alta
26922    Respuesta alta
26923    Respuesta alta
26924    Respuesta alta
Name: host_response_rate, Length: 26925, dtype: category
Categories (2, object): ['Respuesta baja' < 'Respuesta alta']

host_total_listings_count

In [9]:
Max=df["host_total_listings_count"].max()
Min=df["host_total_listings_count"].min()
Limites=[Min, Max]
Limites

[1.0, 468.0]

In [10]:

#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(0.9, 468.1,3)
intervalos

#Crear las categorías
categorias=["Aceptacion baja", "Aceptacion alta"]

df["host_total_listings_count"]=pd.cut(x=df["host_total_listings_count"], bins=intervalos, labels=categorias)

df["host_total_listings_count"]

0        Aceptacion baja
1        Aceptacion baja
2        Aceptacion baja
3        Aceptacion baja
4        Aceptacion baja
              ...       
26920    Aceptacion baja
26921    Aceptacion baja
26922    Aceptacion baja
26923    Aceptacion baja
26924    Aceptacion baja
Name: host_total_listings_count, Length: 26925, dtype: category
Categories (2, object): ['Aceptacion baja' < 'Aceptacion alta']

number_of_reviews

In [11]:
Max=df["number_of_reviews"].max()
Min=df["number_of_reviews"].min()
Limites=[Min, Max]
Limites

[0.0, 294.0]

In [12]:

#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(-0.1, 294.1,3)
intervalos

#Crear las categorías
categorias=["Reseñas bajas", "Reseñas altas"]

df["number_of_reviews"]=pd.cut(x=df["number_of_reviews"], bins=intervalos, labels=categorias)

df["number_of_reviews"]

0        Reseñas bajas
1        Reseñas bajas
2        Reseñas altas
3        Reseñas bajas
4        Reseñas bajas
             ...      
26920    Reseñas bajas
26921    Reseñas bajas
26922    Reseñas altas
26923    Reseñas bajas
26924    Reseñas bajas
Name: number_of_reviews, Length: 26925, dtype: category
Categories (2, object): ['Reseñas bajas' < 'Reseñas altas']

latitude

In [13]:
Max=df["latitude"].max()
Min=df["latitude"].min()
Limites=[Min, Max]
Limites

[40.35107, 40.49229]

In [14]:

#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(40.34, 40.50,3)
intervalos

#Crear las categorías
categorias=["Latitud bajas", "Latitud altas"]

df["latitude"]=pd.cut(x=df["latitude"], bins=intervalos, labels=categorias)

df["latitude"]


0        Latitud bajas
1        Latitud bajas
2        Latitud bajas
3        Latitud bajas
4        Latitud altas
             ...      
26920    Latitud bajas
26921    Latitud altas
26922    Latitud bajas
26923    Latitud bajas
26924    Latitud altas
Name: latitude, Length: 26925, dtype: category
Categories (2, object): ['Latitud bajas' < 'Latitud altas']

In [ ]:
df =df.fillna(method="bfill")
df =df.fillna(method="ffill")
df.isnull().sum()

<ipython-input-123-f51a50de52de>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="bfill")
<ipython-input-123-f51a50de52de>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="ffill")


Unnamed: 0                   0
host_response_rate           0
host_acceptance_rate         0
host_total_listings_count    0
latitude                     0
accommodates                 0
bathrooms                    0
minimum_nights               0
number_of_reviews            0
bedrooms                     0
reviews_per_month            0
price                        0
host_is_superhost            0
host_has_profile_pic         0
host_identity_verified       0
has_availability             0
instant_bookable             0
dtype: int64

---------------

---------------

---------------

Regresión logistica

host_acceptance_rate

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["host_acceptance_rate"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[7363    0]
 [ 715    0]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Aceptacion alta")
print("precision del modelo:")
print(precision)

In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

In [ ]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Aceptacion alta")
print("sensibilidad del modelo")
print(sensibilidad)

host_response_rate

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["host_response_rate"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[7812    0]
 [ 266    0]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Respuesta alta")
print("precision del modelo:")
print(precision)

In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

In [ ]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Respuesta alta")
print("sensibilidad del modelo")
print(sensibilidad)

host_total_listings_count

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["host_total_listings_count"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  463]
 [   0 7615]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Aceptacion alta")
print("precision del modelo:")
print(precision)

In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

In [ ]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Aceptacion alta")
print("sensibilidad del modelo")
print(sensibilidad)

number_of_reviews

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["number_of_reviews"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  593]
 [   0 7485]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Reseñas altas")
print("precision del modelo:")
print(precision)

In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

In [ ]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Reseñas altas")
print("sensibilidad del modelo")
print(sensibilidad)

latitude

In [ ]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["latitude"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[  53 3636]
 [  81 4308]]


In [ ]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Latitud altas")
print("precision del modelo:")
print(precision)

In [ ]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

In [ ]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Latitud altas")
print("sensibilidad del modelo")
print(sensibilidad)