In [1]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#Cargar archivo csv
df=pd.read_csv('mexico_limpio.csv')
df.head(3)


Unnamed: 0  host_listings_count  host_total_listings_count  latitude  \
0           0                  3.0                        6.0  19.42063   
1           1                  1.0                        1.0  19.38283   
2           2                 17.0                       17.0  19.41162   

   longitude  accommodates  bathrooms  bedrooms  beds   price  ...  \
0  -99.16586           2.0        1.0       1.0   2.0  1652.0  ...   
1  -99.20000           2.0        1.0       1.0   1.0  3663.0  ...   
2  -99.17794           3.1        1.4       5.0   1.8  1314.4  ...   

         room_type  bathrooms_text  \
0  Entire home/apt          1 bath   
1  Entire home/apt          1 bath   
2  Entire home/apt       5.5 baths   

                                           amenities  calendar_updated  \
0  ["40 inch HDTV with Amazon Prime Video, Netfli...             nulos   
1  ["Hot water", "Washer", "Bed linens", "Wifi", ...             nulos   
2  ["Wifi", "Coffee maker: Nespresso", "Host gree...             nulos   

   has_availability  calendar_last_scraped  first_review  last_review  \
0                 t             2024-06-28    2013-03-30   2024-04-17   
1                 t             2024-06-27    2013-03-30   2024-04-17   
2                 t             2024-06-28    2011-11-09   2023-03-26   

   license  instant_bookable  
0    nulos                 f  
1    nulos                 f  
2    nulos                 f  

[3 rows x 112 columns]

In [13]:
df['host_is_superhost'] = df['host_is_superhost'].replace({
    't': 'yes',
    'f': 'no',
    'VALIDACIÓN PENDIENTE': np.nan
})

df['host_has_profile_pic'] = df['host_has_profile_pic'].replace({
    't': 'yes',
    'f': 'no',
    'INFORMACIÓN FALTANTE': np.nan
})

df['host_identity_verified'] = df['host_identity_verified'].replace({
    't': 'yes',
    'f': 'no',
    'INFORMACIÓN FALTANTE': np.nan
})

df['has_availability'] = df['has_availability'].replace({
    't': 'yes',
    'f': 'no',
    'INFORMACIÓN NO DISPONIBLE': np.nan
})

df['instant_bookable'] = df['instant_bookable'].replace({
    't': 'yes',
    'f': 'no',
    'INFORMACIÓN NO DISPONIBLE': np.nan
})

df =df.fillna(method="bfill")
df =df.fillna(method="ffill")

<ipython-input-13-d98a12bdaf1e>:31: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="bfill")
<ipython-input-13-d98a12bdaf1e>:32: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df =df.fillna(method="ffill")


In [14]:
df['host_has_profile_pic'].unique()

array(['yes', 'no'], dtype=object)

In [16]:
df["host_has_profile_pic"].head(10)

0    yes
1    yes
2    yes
3    yes
4    yes
5    yes
6    yes
7    yes
8    yes
9    yes
Name: host_has_profile_pic, dtype: object

Modelo 1 host is super host

In [17]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "reviews_per_month", "bedrooms"]]
Var_Dep=df["host_is_superhost"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[4110  691]
 [2311  849]]


In [18]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="yes")
print("precision del modelo:")
print(precision)

precision del modelo:
0.5512987012987013


In [19]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.6229116945107399


In [20]:
#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
0.26867088607594936


modelo 2 host has profile pic

In [21]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "reviews_per_month", "bedrooms"]]
Var_Dep=df["host_has_profile_pic"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  134]
 [   0 7827]]


In [22]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="yes")
print("precision del modelo:")
print(precision)

precision del modelo:
0.9831679437256626


In [23]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.9831679437256626


In [24]:
#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
1.0


modelo 3 host identity verify

In [25]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "reviews_per_month", "bedrooms"]]
Var_Dep=df["host_identity_verified"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  311]
 [   0 7650]]


In [26]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="yes")
print("precision del modelo:")
print(precision)

precision del modelo:
0.9609345559603065


In [27]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.9609345559603065


In [28]:
#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
1.0


modelo 4 has availability

In [29]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "reviews_per_month", "bedrooms"]]
Var_Dep=df["has_availability"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0   12]
 [   0 7949]]


In [30]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="yes")
print("precision del modelo:")
print(precision)

precision del modelo:
0.998492651676925


In [31]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.998492651676925


In [32]:
#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
1.0


**creación de categorias a partir de clases**

host acceptance rate

In [37]:
#Reemplazamos el % en la columna host_acceptance_rate para que se vuelva numerica
df['host_acceptance_rate'] = df['host_acceptance_rate'].str.replace('%', '', regex=False)
df['host_acceptance_rate'] = pd.to_numeric(df['host_acceptance_rate'])

In [38]:
#Reemplazamos el $ en la columna host_response_rate para que se vuelva numerica
df['host_response_rate'] = df['host_response_rate'].str.replace('%', '', regex=False)
df['host_response_rate'] = pd.to_numeric(df['host_response_rate'])

In [39]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

#calcular la sensibilidad
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="yes")
print("sensibilidad del modelo")
print(sensibilidad)

Max=df["host_acceptance_rate"].max()
Min=df["host_acceptance_rate"].min()

# Convert Min and Max to numeric type
Min = pd.to_numeric(Min)
Max = pd.to_numeric(Max)

Limites=[Min, Max]

#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(Min,Max,3)
intervalos

#Crear las categorías
categorias=["Aceptacion baja", "Aceptacion alta"]

df["host_acceptance_rate"]=pd.cut(x=df["host_acceptance_rate"], bins=intervalos, labels=categorias)

df["host_acceptance_rate"]

exactitud del modelo
0.998492651676925
sensibilidad del modelo
1.0


0        Aceptacion alta
1        Aceptacion alta
2        Aceptacion alta
3        Aceptacion alta
4        Aceptacion alta
              ...       
26531    Aceptacion alta
26532    Aceptacion alta
26533    Aceptacion alta
26534    Aceptacion alta
26535    Aceptacion alta
Name: host_acceptance_rate, Length: 26536, dtype: category
Categories (2, object): ['Aceptacion baja' < 'Aceptacion alta']

host respond rate

In [40]:
Max=df["host_response_rate"].max()
Min=df["host_response_rate"].min()
Limites=[Min, Max]

#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(Min, Max,3)
intervalos

#Crear las categorías
categorias=["Respuesta baja", "Respuesta alta"]

df["host_response_rate"]=pd.cut(x=df["host_response_rate"], bins=intervalos, labels=categorias)

df["host_response_rate"]

0        Respuesta alta
1                   NaN
2        Respuesta alta
3        Respuesta alta
4        Respuesta alta
              ...      
26531    Respuesta alta
26532    Respuesta alta
26533    Respuesta alta
26534    Respuesta alta
26535    Respuesta alta
Name: host_response_rate, Length: 26536, dtype: category
Categories (2, object): ['Respuesta baja' < 'Respuesta alta']

host total listings counts

In [41]:
Max=df["host_total_listings_count"].max()
Min=df["host_total_listings_count"].min()
Limites=[Min, Max]

#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(Min, Max,3)
intervalos

#Crear las categorías
categorias=["Aceptacion baja", "Aceptacion alta"]

df["host_total_listings_count"]=pd.cut(x=df["host_total_listings_count"], bins=intervalos, labels=categorias)

df["host_total_listings_count"]

0        Aceptacion baja
1                    NaN
2        Aceptacion baja
3        Aceptacion baja
4        Aceptacion baja
              ...       
26531    Aceptacion baja
26532    Aceptacion baja
26533    Aceptacion baja
26534    Aceptacion baja
26535    Aceptacion alta
Name: host_total_listings_count, Length: 26536, dtype: category
Categories (2, object): ['Aceptacion baja' < 'Aceptacion alta']

number of reviews

In [42]:
Max=df["number_of_reviews"].max()
Min=df["number_of_reviews"].min()
Limites=[Min, Max]

#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(Min, Max,3)
intervalos

#Crear las categorías
categorias=["Reseñas bajas", "Reseñas altas"]

df["number_of_reviews"]=pd.cut(x=df["number_of_reviews"], bins=intervalos, labels=categorias)

df["number_of_reviews"]

0        Reseñas bajas
1                  NaN
2        Reseñas bajas
3        Reseñas altas
4        Reseñas bajas
             ...      
26531              NaN
26532              NaN
26533              NaN
26534              NaN
26535              NaN
Name: number_of_reviews, Length: 26536, dtype: category
Categories (2, object): ['Reseñas bajas' < 'Reseñas altas']

latitude

In [43]:
Max=df["latitude"].max()
Min=df["latitude"].min()
Limites=[Min, Max]

#categorizar las variables
#declarar dos intervalos

intervalos=np.linspace(Min, Max,3)
intervalos

#Crear las categorías
categorias=["Latitud bajas", "Latitud altas"]

df["latitude"]=pd.cut(x=df["latitude"], bins=intervalos, labels=categorias)

df["latitude"]

0        Latitud altas
1        Latitud bajas
2        Latitud altas
3        Latitud altas
4        Latitud altas
             ...      
26531    Latitud altas
26532    Latitud altas
26533    Latitud altas
26534    Latitud altas
26535    Latitud altas
Name: latitude, Length: 26536, dtype: category
Categories (2, object): ['Latitud bajas' < 'Latitud altas']

regresion logistica

host acceptance rate

In [45]:
df.dropna(inplace=True)

In [47]:
df.isnull().sum()

Unnamed: 0                   0
host_listings_count          0
host_total_listings_count    0
latitude                     0
longitude                    0
                            ..
calendar_last_scraped        0
first_review                 0
last_review                  0
license                      0
instant_bookable             0
Length: 112, dtype: int64

In [48]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["host_acceptance_rate"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[5312    0]
 [ 141    0]]


In [50]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Aceptacion alta")
print("precision del modelo:")
print(precision)

precision del modelo:
0.9741426737575647


In [51]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.9741426737575647


In [53]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Aceptacion alta")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
1.0


host respond rate

In [54]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["host_response_rate"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[5372    0]
 [  81    0]]


In [56]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Respuesta alta")
print("precision del modelo:")
print(precision)

precision del modelo:
0.9851457913075371


In [57]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.9851457913075371


In [58]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Respuesta alta")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
1.0


host total listings counts

In [59]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["host_total_listings_count"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  176]
 [   0 5277]]


In [62]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Aceptacion baja")
print("precision del modelo:")
print(precision)

precision del modelo:
0.9677241885200807


In [63]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.9677241885200807


In [64]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Aceptacion baja")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
1.0


number of reviews

In [65]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["number_of_reviews"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  427]
 [   0 5026]]


In [68]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Reseñas bajas")
print("precision del modelo:")
print(precision)

precision del modelo:
0.9216944801026957


In [69]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.9216944801026957


In [70]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Reseñas bajas")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
1.0


latitude

In [71]:
#Declarar las variables independientes y la dependiente
Vars_Indep=df[["price", "accommodates", "bedrooms"]]
Var_Dep=df["latitude"]
X=Vars_Indep
y=Var_Dep

#Dividimos el conjunto de datos
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=None)

#Se escalan los datos
escalar=StandardScaler()
X_train=escalar.fit_transform(X_train)
X_test=escalar.fit_transform(X_test)

#definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo=LogisticRegression()

#Entrenar el modelo
algoritmo.fit(X_train, y_train)

y_pred=algoritmo.predict(X_test)
from sklearn.metrics import confusion_matrix
matriz=confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[3891   21]
 [1530   11]]


In [73]:
#calcular precision del modelo
from sklearn.metrics import precision_score
precision=precision_score(y_test, y_pred, average="binary", pos_label="Latitud altas")
print("precision del modelo:")
print(precision)

precision del modelo:
0.7177642501383509


In [74]:
#calcular exactitud
from sklearn.metrics import accuracy_score
exactitud=accuracy_score(y_test, y_pred)
print("exactitud del modelo")
print(exactitud)

exactitud del modelo
0.7155694113332111


In [75]:
from sklearn.metrics import recall_score

sensibilidad=recall_score(y_test, y_pred, average="binary", pos_label="Latitud altas")
print("sensibilidad del modelo")
print(sensibilidad)

sensibilidad del modelo
0.9946319018404908
